-- Referrals: the single canonical table every dashboard reads from.
--
-- journey_status and outcome are deliberately separate columns:
--   journey_status tracks WHERE the referral is in the clinic pipeline.
--   outcome records WHY a closed referral ended the way it did, and is only
--   ever set once journey_status = 'closed'. This prevents every closed
--   referral being treated as "lost" in reporting — see the check
--   constraint below and lib/types/referral.ts on the app side.
create type public.journey_status as enum (
  'referral_received',
  'awaiting_consultation',
  'consultation_booked',
  'treatment_recommended',
  'treatment_booked',
  'treatment_completed',
  'closed'
);

create type public.referral_outcome as enum (
  'treatment_successful',
  'ongoing_care',
  'patient_declined',
  'did_not_attend',
  'clinically_unsuitable',
  'referred_elsewhere',
  'other'
);

create type public.contact_method as enum ('phone', 'email', 'either');
create type public.fee_status as enum ('not_eligible', 'pending', 'invoiced', 'paid');

create table if not exists public.referrals (
  id uuid primary key default gen_random_uuid(),
  -- Server-generated by public.generate_referral_reference() (0011) — never
  -- accepted from client input, so it cannot be spoofed or collided.
  reference text not null unique,

  practice_id uuid not null references public.practices (id) on delete restrict,
  created_by_user_id uuid not null references public.profiles (id) on delete restrict,

  patient_first_name text not null check (char_length(trim(patient_first_name)) > 0),
  patient_last_name text not null check (char_length(trim(patient_last_name)) > 0),
  patient_dob date not null check (patient_dob <= current_date),
  patient_phone text not null check (char_length(trim(patient_phone)) > 0),
  patient_email text,
  preferred_contact_method public.contact_method not null default 'either',

  -- Defaults to false everywhere — the referring practice must explicitly
  -- confirm consent in the wizard before a referral can be submitted at all
  -- (also enforced by lib/validation/referral.ts and the app-side wizard).
  patient_consent boolean not null default false,
  consent_confirmed_at timestamptz,
  constraint consent_required check (patient_consent = true),

  treatment_type text not null,
  referral_reason text,
  presenting_symptoms text,
  unaided_visual_acuity text,
  best_corrected_visual_acuity text,

  journey_status public.journey_status not null default 'referral_received',
  outcome public.referral_outcome,
  constraint outcome_only_when_closed check (
    (journey_status = 'closed' and outcome is not null)
    or (journey_status <> 'closed' and outcome is null)
  ),

  fee_amount numeric(10, 2) not null default 0 check (fee_amount >= 0),
  fee_status public.fee_status not null default 'not_eligible',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.referrals is 'Canonical referral record. journey_status = pipeline stage; outcome = why a closed referral ended the way it did.';
comment on column public.referrals.reference is 'Server-generated human-readable reference, e.g. ECL-2026-000123.';

create index if not exists referrals_practice_id_idx on public.referrals (practice_id);
create index if not exists referrals_journey_status_idx on public.referrals (journey_status);
create index if not exists referrals_created_at_idx on public.referrals (created_at desc);
